### ISSUE TITLE
A bug issue.

### ISSUE THREAD

**Issue by CGLemon** [zakki/cgos#1]
I quickly report the bug here. I may send the pull request tomorrow. My python version is ```3.8```. Here is a bug for dict in the version.

```
TypeError: 'type' object is not subscriptable
```

The ```dict``` should be replaced by ```typing.Dict``` in my python version. For example,

```
gme: dict[int, GoGame] = dict()
```

should be

```
from typing import Dict
gme: Dict[int, GoGame] = dict()
```

**Comment by zakki** [comment]
Thank you
