### ISSUE TITLE
The CGOS protocol.

### ISSUE THREAD

**Issue by CGLemon** [zakki/cgos#11]
I want to rewrite the server part in my personal repository in order to simplify the code and much focus on tournament games. It means that I will remove some original features. It may include

* Fully support for original CGOS client and some other tools.
* Remove the data base (sqlite).
* Remove the complexity store path.
* Remove the global object.
* Implement fully asynchronous saving feature (Remove the [#5] to this repository).
* User can control the match game.

There are seven states in the CGOS 

* ```protocol``` : get the current client version
* ```username```: get the user name
* ```password```: get the password
* ```gameover```: end the game
* ```genmove```: get the name move
* ```waiting```: waiting for next game
* ```ok```: do not accept any response

There are two protocol version

* ```v1```: nothing special
* ```e1```: use the analysis command

Any special thing should I notice?

**Comment by zakki** [comment]
> v1: nothing special

I am considering dropping the Tcl/Tk viewer and integrating it into the web for the following reasons.
- A few Tcl/Tk programer.
- Data duplication between database and SGF files.
- Impact of viewer processing load on game player handling.
