### ISSUE TITLE
日本語の解説を表示用の漢字と読み上げ用のひらがなに分けたい

### ISSUE THREAD

**Issue by koshikawa** [zakki/cgos#16]
日本語の解説を表示用の漢字と読み上げ用のひらがなに分けたい。

いまは読み上げのひらがなを重視している。
たとえば小目を「しょうめ」と誤読してしまう対策だが、ひらがなだと違和感あるため、分離する。

**Comment by zakki** [comment]
幾つかレイヤーの違う対応が考えられますが、どうでしょうか？
ウェブアプリでの読み上げ関連はあまり知見がありません。何かいい方法あれば教えてください。

## スクリーンリーダー側対応

読み上げソフトの辞書に小目を登録する。

## comment に入れる

```json
{
  "comment": "ここでは小目にカカリが簡単です。"
}
```
の代わりに
```json
{
  "comment": "ここでは小目(こもく)にカカリが簡単です。"
}
```

## アクセシビリティ対応

wgo.jsにWAI-ARIA対応して、必要な情報があればcgos-genmove_analyzeに追加。

**Comment by koshikawa** [comment]
zakkiさん、ごめんなさい。
リポジトリを間違えてIssueを立ててしまいました。。。
クローズします。
