### ISSUE TITLE
Wrong rating in game list

### ISSUE THREAD

**Issue by Remi-Coulom** [zakki/cgos#9]
The rating of crazy_test in the game it lost on time is wrong:
![Screenshot_20230129_032345](https://user-images.githubusercontent.com/10743760/215333089-dcb07243-9cb4-4d8a-ad13-12e0457f0c6e.png)

**Comment by zakki** [comment]
Both Recent Games in standings.html and Recent Games in cross/crazy_test.html uses same `games` table's br and wr columns.
But cross/crazy_test.html seems to be no problem.
![image](https://user-images.githubusercontent.com/162515/218003217-a827037b-0c0b-42f8-9af7-54d01257e971.png)

http://203.138.189.63/cgos/19x19/cross/crazy_test.html

@yssaya Do you have any idea?

**Comment by yssaya** [comment]
I think this rating bug(only standings.html) has been fixed by zakki-san.

**Comment by zakki** [comment]
I forgot that wdata.txt was corrupted.
https://github.com/zakki/cgos/commit/4a19fe9616715f63811855dc87b32d67b8a06be1
https://github.com/zakki/cgos/commit/fa46ede484ee3849615a8645bf5bab363b259ee2

Reoepn this if wrong rating happend again.

**Comment by zakki** [comment]
When game ended by timeout, a time was assigned to a rating .
https://github.com/zakki/cgos/commit/10aa251d963452e4a9eef60a60118280e36dfa77
